apiVersion: v1
kind: Service
metadata:
  name: canary-demo-metrics
  namespace: default
  labels:
    app: canary-demo
spec:
  selector:
    app: canary-demo
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canary-demo
  namespace: default
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 15s
